config/routes.rb
Rails.application.routes.draw do
  get '/' => 'home#index'
  resources :users do
    resources :photos 
    resources :follows, only: [:create]
  end

  resources :follows, only: [:destroy]
  resources :tags, only: [:create, :destroy]
  resources :comments, only: [:create, :destroy]
  get '/log-in' => "sessions#new"
  post '/log-in' => "sessions#create"
  get '/log-out' => "sessions#destroy", as: :log_out

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :photo
end

app/models/follow.rb
class Follow < ActiveRecord::Base
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/photo.rb
class Photo<ActiveRecord::Base
  belongs_to :user
  has_many :tags, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  validates :title, presence: true,
            length: { maximum: 50 }
end

app/models/tag.rb
class Tag<ActiveRecord::Base
  belongs_to :user
  belongs_to :photo
end

app/models/user.rb
class User<ActiveRecord::Base
  has_many :photos
  has_many :tags
  has_many :comments
  attr_accessor :password
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  validates_confirmation_of :password
  before_save :encrypt_password
  validates :email, uniqueness: true

  validates :email, :presence => true
  def encrypt_password
    self.password_salt = BCrypt::Engine.generate_salt
    self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
  end

  def is_email?
    self.email.include?('@') && self.email.include?('.')
  end

  def self.authenticate(email, password)
    user = User.where(email: email).first
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  has_many :active_follows, class_name:"Follow", foreign_key: "follower_id", dependent: :destroy

  has_many :passive_follows, class_name: "Follow", foreign_key: "followed_id", dependent: :destroy

  has_many :following, through: :active_follows, source: :followed
  has_many :followers, through: :passive_follows, source: :follower

  def follow(user)
    active_follows.create(followed_id: user.id)
  end

  def unfollow(user)
    active_follows.find_by(followed_id: user.id).destroy
  end

  def following?(user)
    following.include?(user)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    redirect_to "/"
  end

  def create
    @user = User.find(params[:comment][:user_id])
    @comment = Comment.create({user_id: params[:comment][:user_id], photo_id: params[:comment][:photo_id], body: params[:comment][:body]})
    redirect_to user_path(session[:user_id])
  end

end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController

  def create
    @user = User.find(params[:user_id])
    current_user.follow(@user)
    redirect_to(current_user)
  end

  def destroy
    @rel = User.find(params[:id])
    current_user.unfollow(@rel)
    redirect_to(current_user)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  def show
    @comment = Comment.new
    @photo = Photo.find(params[:id])
    @user = User.find(params[:user_id])
  end

  def create
    @user = User.find(params[:user_id])
    if params[:photo] == nil

      flash[:alert] = "Please upload a photo"
      redirect_to :back
    else
    @photo = Photo.create(photo_params)
      @photo.user_id = @user.id
      @photo.save
      flash[:notice] = "Successfully uploaded a photo"
      redirect_to user_path(@user)
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    @photo = Photo.find(params[:id])
    @photo.destroy
    flash[:notice] = "Photo '#{@photo.title}' deleted."
    redirect_to user_path(@user)
  end

  def new
    @user = User.find(params[:user_id])
    @photo = Photo.create()
  end

  private
  def photo_params
    params.require(:photo).permit(:image, :title)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.authenticate(params[:email], params[:password])
    if @user
      flash[:notice] = "You've been logged in."
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      flash[:alert] = "There was a problem logging you in!"
      redirect_to log_in_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You've been logged out successfully."
    redirect_to "/"
  end

end

app/controllers/tags_controller.rb
class TagsController<ActionController::Base
  def new
    redirect_to "/"
  end

  def create
    @user = User.find(params[:tag][:user_id])
    @tag = Tag.create({user_id: params[:tag][:user_id], photo_id: params[:tag][:photo_id]})
    redirect_to user_path(session[:user_id])
  end




end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def create
    @user = User.new(user_params)
    @user.valid?
    if !@user.is_email?
      flash[:alert] = "Input a properly formatted email."
      redirect_to :back
    elsif @user.errors.messages[:email] != nil
      flash[:notice]= "That email " + @user.errors.messages[:email].first
      redirect_to :back
    elsif @user.save
      flash[:notice]= "Signup successful. Welcome to the site!"
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      flash[:alert] = "There was a problem creating your account. Please try again."
      redirect_to :back
    end
  end


  def new
  end


  def index
    @users = User.all
  end


  def show
    @users = User.all
    @user = User.find(params[:id])
    @tag = Tag.new
    @comment = Comment.new
  end


  private

    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :avatar)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.haml
%h1 Treegram
%h2 Your Favorite Tree Photosharing Service
.row
  .col-sm-4
    = link_to 'Login', log_in_path, class: ["btn", "btn-success", 'btn-lg']
    = link_to 'Sign Up', new_user_path, class: ['btn', 'btn-success', 'btn-lg']
  .col-sm-7
    = image_tag "background.jpg"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title PhotoShare
    %link{:href => "http://fonts.googleapis.com/css?family=Open+Sans+Condensed:300", :rel => "stylesheet", :type => "text/css"}/
    %link{:href => "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css", :rel => "stylesheet"}/
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .container
      = flash[:alert]
      = flash[:notice]
      = yield

app/views/photos/new.html.haml
%h1 Add a Photo
= form_for Photo.new(), :url => user_photos_path, :html => {:multipart => true} do |form|
  = form.label :title
  = form.text_field :title
  = form.file_field :image
  = form.submit 'Upload'

app/views/photos/show.html.haml
%h2{:align => "left"}#{"Comments for image with title: " + @photo.title}
-@photo.comments.order(created_at: :desc).each do |comment|
  %strong= comment.user.email
  = comment.body
  %br

%h4 Enter a new comment
= form_for @comment do |f|
  = f.hidden_field :photo_id, value: @photo.id
  = f.hidden_field :user_id, value: @user.id
  = f.label :body
  = f.text_area :body
  %br
  = f.submit 'Save comment'

app/views/users/index.html.haml
.row.top_row
  .col-sm-6.user_att
    %h2= User.find(params[:id]).email
    - if User.find(params[:id]).avatar_file_name
      = image_tag User.find(params[:id]).avatar.url(:thumb)
      %br
      %br
      = link_to 'Go Back', user_path(User.find(params[:id])), class: ['btn', 'btn-primary']
  .col-sm-6
    = link_to 'Logout', log_out_path, class: ['btn', 'btn-danger', 'logout_btn']

%br/
%br/
%br/
%br/
%br/
%br/
%br/
%br/
%br/
%br/

%h2{:align => "left"}All Suggestions
%br
%table#users
  %thead
    %tr
      %th User Email
      %th Option

  %tbody
    - @users.each do |user|
      %tr
        %td= user.email
        - if user != current_user
          - if user.followers.include?(User.find(params[:id]))
            %td= button_to "Unfollow", follow_path(user.id), method: :delete, :class => "btn btn-default"
          - else
            %td= button_to "Follow", user_follows_path(user_id: user.id), method: :post, :class => "btn btn-primary"

app/views/users/new.html.haml
%h1 Sign Up
= form_for User.new, class: "form-inline" do |f|
  = f.label :email
  = f.text_field :email
  = f.label :password
  = f.password_field :password
  = f.label :password_confirmation
  = f.password_field :password_confirmation
  %br/
  = f.label :avatar, 'Upload Avatar'
  = f.file_field :avatar
  %br/
  = f.submit "Sign Up"

app/views/users/show.html.haml
.row.top_row
  .col-sm-6.user_att
    %h2= @user.email
    - if @user.avatar_file_name
      = image_tag @user.avatar.url(:thumb)
  .col-sm-6
    = link_to 'Logout', log_out_path, class: ['btn', 'btn-danger', 'logout_btn']
  .row
    = link_to 'Add Photo', new_user_photo_path(@user), class: ['btn', 'btn-success', 'add_photo_btn']
  .row
    = link_to 'All Users', {:action => 'index', :id => @user.id}, class: ['btn', 'btn-primary', 'all_user_btn']
%br/
%br/
%br/
.row
  - if !@user.photos.empty?
    %h1{:align => "center"}
      %i> My Photos
    %br/
    %br/
    %h2#caption Slide Show
    -userPhotos =  @user.photos.sort_by{|e| e.created_at}.reverse
    %img#slide{alt: "",  src: userPhotos.first.image.url(:medium), href: user_photo_path(@user.id, userPhotos.first.id)}
    #slides
      - userPhotos.each  do |photo|
        .well.col-sm-4
          %h4{:align => "left"}
            %b Title: #{photo.title}
          %img{alt: photo.title ,  src: photo.image.url(:medium), href: user_photo_path(@user.id, photo.id)}
          = link_to 'Delete', user_photo_path(@user.id, photo.id), :method => :delete, :confirm => 'Are you sure?'
          = form_for @tag do |f|
            = f.hidden_field :photo_id, value: photo.id
            = f.collection_select :user_id, @users, :id, :email
            = f.submit "Tag User"
          - photo.tags.each do |tag|
            = tag.user.email
          %br
          = link_to 'Add a comment...', user_photo_path(@user.id, photo.id)
          %br
          - photo.comments.each do |comment|
            = comment.user.email
            = comment.body
            %br

  .row
  - if !@user.following.empty?
    %h1{:align => "center"}
      %i> My Followers Photos
      %br
      %br
    - @user.following.each do |followed|
      .row
      - if !followed.photos.empty?
        %h1{:align => "center"}
          %i> photos from #{followed.email}
        %h2#caption Slide Show
        -followerPhotos = followed.photos.sort_by{|e| e.created_at}.reverse
        %img#slide{alt: "",  src:followerPhotos.first.image.url(:medium), href: user_photo_path(@user.id, followerPhotos.first.id) }
        #slides
          - followerPhotos.each  do |photo|
            .well.col-sm-4
              %h4{:align => "left"}
                %b Title: #{photo.title}
              %img{alt: photo.title ,  src: photo.image.url(:medium), href: user_photo_path(@user.id,photo.id)}
              = form_for @tag do |f|
                = f.hidden_field :photo_id, value: photo.id
                = f.collection_select :user_id, @users, :id, :email
                = f.submit "Tag User"
              - photo.tags.each do |tag|
                = tag.user.email
              %br
              = link_to 'Add a comment...', user_photo_path(@user.id, photo.id)
              %br
              - photo.comments.each do |comment|
                = comment.user.email
                = comment.body
                %br